### PR TITLE
FEAT: Use prefect env variables to simplify getting result from flow

### PR DESCRIPTION
**Pull request by anmyachev**

### CODE REVIEW

**Comment by pbchekin** [comment]
I think we can try to set these variables here: https://github.com/intel-ai/icl/blob/main/src/infractl/plugins/prefect_runtime/runtime.py#L293

We use Prefect temporary_settings to set PREFECT_API_URL

```python
with settings.temporary_settings(updates={settings.PREFECT_API_URL: self.prefect_api_url}):
```

**Comment by anmyachev** [comment]
> I think we can try to set these variables here: https://github.com/intel-ai/icl/blob/main/src/infractl/plugins/prefect_runtime/runtime.py#L293
> 
> We use Prefect temporary_settings to set PREFECT_API_URL
> 
> ```python
> with settings.temporary_settings(updates={settings.PREFECT_API_URL: self.prefect_api_url}):
> ```

I already tried in https://github.com/intel-ai/icl/pull/26/commits/020e2fa28a483405375f0c37466890531632ce60 (with several fixes after that). Looks like it doesn't work.

**Comment by anmyachev** [comment]
Blocked by #29

**Review by pbchekin — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
